In [3]:
import torch
import torch.nn.functional as F

## Softmax

In [20]:
data = torch.FloatTensor([1, 2, 1])
F.softmax(data, dim=-1)

tensor([0.2119, 0.5761, 0.2119])

In [21]:
data = torch.FloatTensor([
    [1, 2, 1],
    [2, 3, 4]
])
F.softmax(data, dim=-1)

tensor([[0.2119, 0.5761, 0.2119],
        [0.0900, 0.2447, 0.6652]])

In [38]:
# let implement a softmax function
def calc_softmax(data, dim=-1):
    e_data = torch.exp(data)
    return e_data / torch.sum(e_data, dim=dim, keepdim=True)

data = torch.FloatTensor([1, 2, 1])
calc_softmax(data)

tensor([0.2119, 0.5761, 0.2119])

In [39]:
data = torch.FloatTensor([
    [1, 2, 1],
    [2, 3, 4]
])
calc_softmax(data)

tensor([[0.2119, 0.5761, 0.2119],
        [0.0900, 0.2447, 0.6652]])